### ISSUE TITLE
YOUR GOOGLE DRIVE SECRET KEY IS PUBLICLY AVAILABLE

### ISSUE THREAD

**Issue by karuppiah7890** [abhinit/google_drive_file_upload#1]
I could get them from this commit : https://github.com/abhinit/google_drive_file_upload/commit/713678516e05d32d799ca293210c45236266f85f 

And see your files too : 

![hack](https://user-images.githubusercontent.com/12808424/28860547-b1c2dbde-777a-11e7-809a-77b75be7539c.png)

I didn't misuse it though. Just try to get rid of the above commit.

**Comment by abhinit** [comment]
Thanks a lot for this! It was a major mistake, I have disabled the api keys and removed the commits. I checked and fortunately there were no intrusions before you discovered this. Thanks!
